name: lint_on_pr

on:
  push:
    branches-ignore:
    - master
    - main
  pull_request:

jobs:
  lint_on_pr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: install go
      uses: actions/setup-go@v2

    - name: install golangci-lint
      run: |
        set -euo pipefail
        lint_version="$(curl -s -o /dev/null -w '%{redirect_url}' 'https://github.com/golangci/golangci-lint/releases/latest' | sed 's/.*releases\/tag\///g')"
        curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b "$GITHUB_WORKSPACE" "$lint_version"

    - name: install lint-gomko-all
      run: GOBIN="$GITHUB_WORKSPACE/bin" go get -u github.com/mkorenkov/lint-gomko/cmd/lint-gomko-all

    - name: run golangci-lint
      run: $GITHUB_WORKSPACE/golangci-lint run --new-from-rev origin/master -c .golangci.yml ./...

    - name: run lint-gomko-all
      run: IGNORE="testdata/*,vendor/*,*.twirp.go,*_test.go" go vet -vettool "$GITHUB_WORKSPACE/bin/lint-gomko-all"
